#!/bin/bash

function show_usage () {
    printf "Usage: $0 [OPTION]... SOURCE TARGET\n"
    printf "Convert SOURCE aax File to TARGET mp4 File using ffmpeg\n"
    printf "\n"
    printf "Options:\n"
    printf " -b | --activation-bytes, activaton bytes to pass to ffmpeg\n"
    exit
}

while [ ! -z "$1" ];do
   case "$1" in
        -h|--help)
          show_usage
          ;;
        -b|--activation-bytes)
          shift
          ACTIVATION_BYTES="$1"
          ;;
        *)
          SOURCE="$1"
          shift
          TARGET="$1"
          if [[ -z "$SOURCE" ]] || [[ -z "$TARGET" ]]
          then
          printf "No SOURCE and/or TARGET specified\n\n"
            show_usage
          fi
   esac
shift
done

if [[ -d "$TARGET" ]] 
then
    ORIGINAL_FILE_NO_PATH=$(basename -- "$SOURCE")
    ORIGINAL_FILE_NAME_NO_EXTENSION="${ORIGINAL_FILE_NO_PATH%.*}"
    if [[ "$TARGET" == */ ]]; then
        printf "directory mit /\n"
        TARGET="$TARGET$ORIGINAL_FILE_NAME_NO_EXTENSION.mp4"
    else
        printf "directory ohne /\n"
        TARGET="$TARGET/$ORIGINAL_FILE_NAME_NO_EXTENSION.mp4"
    fi
fi

ffmpeg -activation_bytes "$ACTIVATION_BYTES" -i "$SOURCE" -vn -c:a copy "$TARGET"

if [[ $? -eq 0 ]]
then
  read -n 1 -p "Remove $SOURCE? [Y|n]" SHOULD_DELETE_SOURCE
  if [[ -z "$SHOULD_DELETE_SOURCE" || "$SHOULD_DELETE_SOURCE" == "Y" || "$SHOULD_DELETE_SOURCE" == "y" ]] 
  then 
    rm $SOURCE
  fi
fi

